### ISSUE TITLE
Automate plugin release

### ISSUE THREAD

**Issue by emilianbold** [foojay2020/nbplugin2#23]
Uploading to Maven Central was quite time consuming last I checked.

This issue should track the various steps involved:

* [ ] Read (I think?) https://central.sonatype.org/pages/ossrh-guide.html for Sonatype signup, etc.
* [ ] Ideally, discoclient could also be used from Maven Central
* [ ] Use GitHub Actions to do a Maven release from the project, ideally using the PGP key as some secret

**Comment by geertjanw** [comment]
https://cwiki.apache.org/confluence/display/NETBEANS/Step+by+step+guide+for+upload+NBM+to+Maven+Central

**Comment by emilianbold** [comment]
I've posted this issue to Sonatype so we can publish to Maven Central eventually

https://issues.sonatype.org/browse/OSSRH-65132

**Comment by emilianbold** [comment]
@geertjanw OK, now Sonatype wants to check we control io.foojay https://central.sonatype.org/pages/producers.html

Not sure which is easier:

In the case of a GitHub groupId (io.github.username), this will be immediately verified provided your project URL matches the requested groupId.
For all other domains, be prepared to verify domain ownership via one of the following methods:
TXT record verification:
This is the fastest route to verification. Simply create a TXT record in your DNS referencing your OSSRH ticket number and your groupId will be approved.
GitHub redirection:
Setup a redirect from your domain to the GitHub URL where you are hosting your project.

Can you add the TXT record?

**Comment by geertjanw** [comment]
Where must the TXT record be added? In foojay.io?

**Comment by emilianbold** [comment]
I didn't do this before but I think so. If you control the DNS to foojay.io you could add a TXT record with the ticket number.

**Comment by emilianbold** [comment]
BTW, if you have an username on sonatype I should also add your name to the list (presumably, so your PGP key is also accepted.)

**Comment by geertjanw** [comment]
What is the ticket number?

If you can tell me what exactly must be added where exactly on foojay.io, I can get it done.

**Comment by emilianbold** [comment]
I wrote it in another comment. It's this ticket https://issues.sonatype.org/browse/OSSRH-65132

So I assume you need a TXT record with either the full URL or maybe just OSSRH-65132 in it.

**Comment by emilianbold** [comment]
For reference, the new ticket was https://issues.sonatype.org/browse/OSSRH-66676

**Comment by emilianbold** [comment]
> https://cwiki.apache.org/confluence/display/NETBEANS/Step+by+step+guide+for+upload+NBM+to+Maven+Central

This was handy in https://github.com/foojay2020/discoclient/pull/4 while releasing discoclient.

**Comment by emilianbold** [comment]
Closing issue since there will be no Maven releases for this one.
