### ISSUE TITLE
Is the Download button needed?

### ISSUE THREAD

**Issue by geertjanw** [foojay2020/nbplugin2#36]
In the Quick tab, after browsing to a location, could the Next button be enabled, which would trigger the download, instead of forcing the user to click the Download button, i.e., that Download button and the action the user takes isn't needed, I think.

**Comment by emilianbold** [comment]
Actually, originally, after Browse... was clicked and a folder selected I immediately started a download.

The Download button seems superfluous but I wonder if having another wizard step doesn't make things too tedious...

**Comment by geertjanw** [comment]
No, I mean, 'simply' enable the Next button, which when clicked starts the download process. If that makes sense.

**Comment by emilianbold** [comment]
I can do that but then Next will move to the next Wizard step which will have a new panel.
