### ISSUE TITLE
Show the full file name of the file that will be downloaded

### ISSUE THREAD

**Issue by geertjanw** [foojay2020/nbplugin2#37]
In the "Connect to OpenJDK Discovery Service" tab, after an OpenJDK version is chosen, and then next is clicked, please show the actual file name of the bundle that will be downloaded, i.e., instead of (or in addition to "You have selected: Java 11", also show the full file name that of the file that is going to be downloaded.

**Comment by emilianbold** [comment]
Ha, there is a reason I'm not doing that -- showing the file requires a roundtrip to the server. But, I'll look into it.
