### ISSUE TITLE
Check if NetBeans requires Java 8 or Java 11

### ISSUE THREAD

**Issue by emilianbold** [foojay2020/nbplugin2#40]
Check if current NetBeans still requires Java 8 or if is Java 11 acceptable.

**Comment by emilianbold** [comment]
It actually says so in the README: https://github.com/apache/netbeans

> Requirements
> *    JDK 8 or 11 (to build NetBeans)
> *    JDK 9 or above (to run NetBeans)

So it looks like the plugin will have to use Java 8.

**Comment by geertjanw** [comment]
Gerrit is creating a Java 8 branch of the DiscoClient.

**Comment by geertjanw** [comment]
Get it here: https://github.com/foojay2020/discoclient/actions/runs/636142475

**Comment by emilianbold** [comment]
If the JAR is compiled with Java 11 and uses APIs from Java 11 it will crash at runtime on Java 8. I'll check the Java 8 branch.

**Comment by emilianbold** [comment]
We now know we need Java 8.
