### ISSUE TITLE
DiscoClient cannot be included in NetBeans

### ISSUE THREAD

**Issue by emilianbold** [foojay2020/nbplugin2#42]
As far as I can tell, NetBeans still expects to build on Java 8. This means that discoclient, which uses that Java 11 HttpClient cannot be included.

If the foojay backend has some documentation we could re-implement discoclient using some Java 8 APIs/libraries like the Apache Commons HttpClient 3.1 which NetBeans already includes.

**Comment by emilianbold** [comment]
Also related to issue #40

**Comment by emilianbold** [comment]
@geertjanw while there is value in having discoclient as a separate JAR for other clients, I think we should just include the code from discoclient in the plugin. It makes no sense to have another "3rd party jar" wrapped in the module.

It might make a bit of sense *if* discoclient were to be published on Maven Central which, right now, it is not.

I'm also mildly wondering if it's worth having these 2 codebases under different licenses. In particular, using discoclient introduces the need for a NOTICE file entry.

**Comment by geertjanw** [comment]
Sure. Makes sense.

**Comment by emilianbold** [comment]
I think this can be closed. discoclient has a java8 branch and is included as a JAR and will be on Maven Central in the future. There isn't much actionable in this issue anymore.
