### ISSUE TITLE
Suggest good default location for download

### ISSUE THREAD

**Issue by geertjanw** [foojay2020/nbplugin2#45]
Rather than letting the user put the download anywhere, provide a logical place to put it as a suggestion, e.g. (on Mac OS X):

/Users/geertjanwielenga/Library/Java/JavaVirtualMachines/openjdk-15.0.2

**Comment by emilianbold** [comment]
* macOS: Library/Java/JavaVirtualMachines
* Linux: $XDG_DATA_HOME/jvm/ or  $HOME/.local/share
* Windows: %LOCALAPPDATA%/Java or AppData/Local
